inherit_gem:
  rubocop_defaults: .rubocop.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.6

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Lint/NonDeterministicRequireOrder:
  Enabled: false

RSpec/ExpectActual:
  Exclude:
    - spec/number_muncher/parser_spec.rb
